# Generated by Django 5.1.4 on 2025-01-03 04:52

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser_bio_customuser_service_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('service_location', models.CharField(help_text='Cities or zip codes you serve', max_length=200)),
                ('services_offered', multiselectfield.db.fields.MultiSelectField(choices=[('lawn_mowing', 'Lawn Mowing'), ('landscaping', 'Landscaping'), ('pest_control', 'Pest Control'), ('garden_maintenance', 'Garden Maintenance'), ('tree_trimming', 'Tree Trimming'), ('irrigation', 'Irrigation Services'), ('planting', 'Planting Services')], max_length=89)),
                ('available_days', multiselectfield.db.fields.MultiSelectField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=56)),
                ('working_hours_start', models.TimeField()),
                ('working_hours_end', models.TimeField()),
                ('years_of_experience', models.PositiveIntegerField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate in $', max_digits=6)),
                ('flat_rate_services', models.TextField(blank=True, help_text='List any flat-rate services and their prices')),
                ('portfolio', models.TextField(blank=True, help_text='Describe your past work and experience')),
                ('references', models.TextField(blank=True, help_text='List any references or testimonials')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
