# Generated by Django 5.1.4 on 2025-01-03 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_booking_address_remove_booking_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='service',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='service',
            name='total_reviews',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('lawn', 'Lawn Care'), ('garden', 'Garden Maintenance'), ('landscape', 'Landscaping'), ('tree', 'Tree Service'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(help_text='Service area or location', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
